package com.dustinhendriks.andme.utils;

public class DefaultIconPack {
    private static final String DEFAULT_THEME = "{ \"bindings\": ["
            + "{\"packageName\": \"com.android.chrome\", \"fileName\": \"googlechrome.svg\"},"
            + "{\"packageName\": \"com.facebook.katana\", \"fileName\": \"facebook.svg\"},"
            + "{\"packageName\": \"com.instagram.android\", \"fileName\": \"instagram.svg\"},"
            + "{\"packageName\": \"com.whatsapp\", \"fileName\": \"whatsapp.svg\"},"
            + "{\"packageName\": \"com.zhiliaoapp.musically\", \"fileName\": \"tiktok.svg\"},"
            + "{\"packageName\": \"com.google.android.youtube\", \"fileName\": \"youtube.svg\"},"
            + "{\"packageName\": \"com.google.android.apps.maps\", \"fileName\": \"googlemaps.svg\"},"
            + "{\"packageName\": \"com.google.android.apps.photos\", \"fileName\": \"googlephotos.svg\"},"
            + "{\"packageName\": \"com.snapchat.android\", \"fileName\": \"snapchat.svg\"},"
            + "{\"packageName\": \"com.spotify.music\", \"fileName\": \"spotify.svg\"},"
            + "{\"packageName\": \"org.telegram.messenger\", \"fileName\": \"telegram.svg\"},"
            + "{\"packageName\": \"com.amazon.mShop.android.shopping\", \"fileName\": \"amazon.svg\"},"
            + "{\"packageName\": \"com.netflix.mediaclient\", \"fileName\": \"netflix.svg\"},"
            + "{\"packageName\": \"com.twitter.android\", \"fileName\": \"twitter.svg\"},"
            + "{\"packageName\": \"com.microsoft.office.outlook\", \"fileName\": \"microsoftoutlook.svg\"},"
            + "{\"packageName\": \"com.google.android.apps.docs\", \"fileName\": \"googledrive.svg\"},"
            + "{\"packageName\": \"com.google.android.gm\", \"fileName\": \"gmail.svg\"},"
            + "{\"packageName\": \"com.google.android.calendar\", \"fileName\": \"googlecalendar.svg\"},"
            + "{\"packageName\": \"com.pinterest\", \"fileName\": \"pinterest.svg\"},"
            + "{\"packageName\": \"com.reddit.frontpage\", \"fileName\": \"reddit.svg\"},"
            + "{\"packageName\": \"com.discord\", \"fileName\": \"discord.svg\"},"
            + "{\"packageName\": \"com.whatsapp.w4b\", \"fileName\": \"whatsapp.svg\"},"
            + "{\"packageName\": \"com.hbo.hbonow\", \"fileName\": \"hbo.svg\"},"
            + "{\"packageName\": \"com.zzkko\", \"fileName\": \"shein.svg\"},"
            + "{\"packageName\": \"com.temu\", \"fileName\": \"temu.svg\"},"
            + "{\"packageName\": \"us.zoom.videomeetings\", \"fileName\": \"zoom.svg\"},"
            + "{\"packageName\": \"com.linkedin.android\", \"fileName\": \"linkedin.svg\"},"
            + "{\"packageName\": \"com.ubercab\", \"fileName\": \"uber.svg\"},"
            + "{\"packageName\": \"com.google.android.gms\", \"fileName\": \"googleplay.svg\"},"
            + "{\"packageName\": \"com.google.android.apps.walletnfcrel\", \"fileName\": \"googlepay.svg\"},"
            + "{\"packageName\": \"com.duolingo\", \"fileName\": \"duolingo.svg\"},"
            + "{\"packageName\": \"com.lemon.lvoverseas\", \"fileName\": \"capcut.svg\"},"
            + "{\"packageName\": \"com.sec.android.app.sbrowser\", \"fileName\": \"samsung.svg\"},"
            + "{\"packageName\": \"com.squareup.cash\", \"fileName\": \"cashapp.svg\"},"
            + "{\"packageName\": \"com.paypal.android.p2pmobile\", \"fileName\": \"paypal.svg\"},"
            + "{\"packageName\": \"com.venmo\", \"fileName\": \"venmo.svg\"},"
            + "{\"packageName\": \"com.waze\", \"fileName\": \"waze.svg\"},"
            + "{\"packageName\": \"com.soundcloud.android\", \"fileName\": \"soundcloud.svg\"},"
            + "{\"packageName\": \"com.fitbit.FitbitMobile\", \"fileName\": \"fitbit.svg\"},"
            + "{\"packageName\": \"com.shazam.android\", \"fileName\": \"shazam.svg\"},"
            + "{\"packageName\": \"tv.twitch.android.app\", \"fileName\": \"twitch.svg\"},"
            + "{\"packageName\": \"com.Slack\", \"fileName\": \"slack.svg\"},"
            + "{\"packageName\": \"com.bitstrips.imoji\", \"fileName\": \"bitmoji.svg\"},"
            + "{\"packageName\": \"com.tumblr\", \"fileName\": \"tumblr.svg\"},"
            + "{\"packageName\": \"com.robinhood.android\", \"fileName\": \"robinhood.svg\"},"
            + "{\"packageName\": \"kik.android\", \"fileName\": \"kik.svg\"},"
            + "{\"packageName\": \"co.hinge.app\", \"fileName\": \"hinge.svg\"},"
            + "{\"packageName\": \"com.bumble.app\", \"fileName\": \"bumble.svg\"},"
            + "{\"packageName\": \"com.zhiliaoapp.musically.go\", \"fileName\": \"tiktok.svg\"},"
            + "{\"packageName\": \"com.tencent.mm\", \"fileName\": \"wechat.svg\"},"
            + "{\"packageName\": \"com.alibaba.aliexpresshd\", \"fileName\": \"aliexpress.svg\"},"
            + "{\"packageName\": \"com.shopify.mobile\", \"fileName\": \"shopify.svg\"},"
            + "{\"packageName\": \"com.clubhouse.app\", \"fileName\": \"clubhouse.svg\"},"
            + "{\"packageName\": \"com.etsy.android\", \"fileName\": \"etsy.svg\"},"
            + "{\"packageName\": \"com.poshmark.app\", \"fileName\": \"poshmark.svg\"},"
            + "{\"packageName\": \"com.myfitnesspal.android\", \"fileName\": \"myfitnesspal.svg\"},"
            + "{\"packageName\": \"com.strava\", \"fileName\": \"strava.svg\"},"
            + "{\"packageName\": \"com.asana.app\", \"fileName\": \"asana.svg\"},"
            + "{\"packageName\": \"notion.id\", \"fileName\": \"notion.svg\"},"
            + "{\"packageName\": \"com.todoist\", \"fileName\": \"todoist.svg\"},"
            + "{\"packageName\": \"com.trello\", \"fileName\": \"trello.svg\"},"
            + "{\"packageName\": \"com.google.android.keep\", \"fileName\": \"googlekeep.svg\"},"
            + "{\"packageName\": \"com.evernote\", \"fileName\": \"evernote.svg\"},"
            + "{\"packageName\": \"com.microsoft.teams\", \"fileName\": \"microsoftteams.svg\"},"
            + "{\"packageName\": \"us.zoom.videomeetings\", \"fileName\": \"zoom.svg\"},"
            + "{\"packageName\": \"com.duosecurity.duomobile\", \"fileName\": \"duo.svg\"},"
            + "{\"packageName\": \"com.lastpass.lpandroid\", \"fileName\": \"lastpass.svg\"},"
            + "{\"packageName\": \"com.azure.authenticator\", \"fileName\": \"microsoftauthenticator.svg\"},"
            + "{\"packageName\": \"com.x8bit.bitwarden\", \"fileName\": \"bitwarden.svg\"},"
            + "{\"packageName\": \"com.agilebits.onepassword\", \"fileName\": \"onepassword.svg\"},"
            + "{\"packageName\": \"com.dashlane\", \"fileName\": \"dashlane.svg\"},"
            + "{\"packageName\": \"com.nordvpn.android\", \"fileName\": \"nordvpn.svg\"},"
            + "{\"packageName\": \"com.expressvpn.vpn\", \"fileName\": \"expressvpn.svg\"},"
            + "{\"packageName\": \"ch.protonvpn.android\", \"fileName\": \"protonvpn.svg\"},"
            + "{\"packageName\": \"org.thoughtcrime.securesms\", \"fileName\": \"signal.svg\"},"
            + "{\"packageName\": \"com.viber.voip\", \"fileName\": \"viber.svg\"},"
            + "{\"packageName\": \"jp.naver.line.android\", \"fileName\": \"line.svg\"},"
            + "{\"packageName\": \"com.kakao.talk\", \"fileName\": \"kakaotalk.svg\"},"
            + "{\"packageName\": \"com.skype.raider\", \"fileName\": \"skype.svg\"}"
            + "]}";


    public static String getDefaultIconPack() {
        return DEFAULT_THEME;
    }
}
